language: php

php:
  - 7.2

dist: trusty
sudo: required

before_script:
  - composer self-update
  - composer clear-cache

before_install:
  - if [[ $TRAVIS_PHP_VERSION != 7.2 ]] ; then phpenv config-rm xdebug.ini; fi

install: travis_retry composer install --no-interaction --prefer-dist --no-suggest

script: ./vendor/bin/phpunit --testsuit=Unit
