sudo: required

language: php

php:
  - 7.2

before_install:
  - sudo apt-get update
  - travis_retry composer self-update

install:
  - travis_retry composer update --prefer-source --prefer-lowest

script:
  - vendor/bin/phpunit

branches:
  only:
    - master
