sudo: required

language: php

php:
  - 7.2

before_install:
  - travis_retry composer self-update

script:
  - ./vendor/bin/phpunit --testsuit=Unit

install:
  - travis_retry composer update --prefer-source

branches:
  only:
    - master
