sudo: required

language: php

php:
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

script:
  - ./vendor/bin/phpunit --testsuit=Unit

install:
  - travis_retry composer update --prefer-source --prefer-lowest --no-interaction --verbose

branches:
  only:
    - master
